<?php
declare(strict_types=1);
return json_decode(<<<'CATALOG'
[
  {
    "id": "touch-panel-9",
    "sku": "TW601090-916",
    "name": "מפסק זכוכית טאץ׳ Z-Wave עד 9 לחצנים TouchWand",
    "description": "כולל חיישן קרבה, 6 מעגלים להזנות ישירות ועד 3 תרחישים. דורש אפס במפסק וקופסת עומק 3 מקום שוכב.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 98000,
    "maxNetCents": null,
    "image": "panel9-rectangular.webp",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 39800
  },
  {
    "id": "glass-1",
    "sku": "Glasswand 1-b w",
    "name": "מפסק זכוכית טאץ׳ מהודר עם לחצן בודד לתאורה",
    "description": "חיווי אור בהפעלה, ללא כיתוב, בצבע לבן. דורש אפס במפסק התאורה מצד החשמלאי.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 45000,
    "maxNetCents": null,
    "image": "glass-1b.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "glass-2",
    "sku": "Glasswand 2-b w",
    "name": "מפסק זכוכית טאץ׳ מהודר עם 2 לחצנים לתאורה",
    "description": "חיווי אור בהפעלה, ללא כיתוב, בצבע לבן. דורש אפס במפסק התאורה מצד החשמלאי.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 45000,
    "maxNetCents": null,
    "image": "glass-2b.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "glass-3",
    "sku": "Glasswand 3-b w",
    "name": "מפסק זכוכית טאץ׳ מהודר עם 3 לחצנים לתאורה",
    "description": "חיווי אור בהפעלה, ללא כיתוב, בצבע לבן. דורש אפס במפסק התאורה מצד החשמלאי.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 45000,
    "maxNetCents": null,
    "image": "glass-3b.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "glass-shutter",
    "sku": "Glasswand 2-shut w",
    "name": "מפסק זכוכית טאץ׳ מהודר לעלייה ולהורדה של תריס",
    "description": "חיווי אור בהפעלה, ללא כיתוב, בצבע לבן. דורש אפס במפסק מצד החשמלאי.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 45000,
    "maxNetCents": null,
    "image": "glass-shutter.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "engraving",
    "sku": "חריטה",
    "name": "חריטה מותאמת על גבי מפסק",
    "description": "יש לעדכן מראש ולפני ביצוע. המחיר למפסק בודד.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 20000,
    "maxNetCents": null,
    "image": "",
    "requiresQuote": false,
    "installationIncluded": true
  },
  {
    "id": "acwand",
    "sku": "TW501000",
    "name": "ACWAND - חיישן טמפרטורה מוגבר לשליטה על מזגן",
    "description": "מתחבר ב-Wi-Fi עם כניסה לשקע חשמלי. דורש שקע חשמל פנוי ומגע יבש בהזנת המזגן מצד החשמלאי.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 49000,
    "maxNetCents": null,
    "image": "sensibo-sky.jpg",
    "requiresQuote": false,
    "installationIncluded": true
  },
  {
    "id": "heater-switch",
    "sku": "129020",
    "name": "מפסק זכוכית Z-Wave 16A לתנור אמבטיה",
    "description": "כולל חיבור וניתוק בנפרד. מותקן במקום מפסק התנור של הקבלן.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 45000,
    "maxNetCents": null,
    "image": "glass-boiler-timer.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "micro-module",
    "sku": "TW303100-916-E",
    "name": "מיקרומודול 230V מאחורי מפסק הקבלן",
    "description": "עד 5 אמפר לערוץ ומקסימום 120 וואט; מתאים לשני מעגלי תאורה צמודים או לתריס אחד.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 29500,
    "maxNetCents": null,
    "image": "micromodule.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "programming",
    "sku": "IFW008",
    "name": "שינויי תכנות למסך המגע הקיים בדירה או תוספת רכיב הפעלה",
    "description": "",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 45000,
    "maxNetCents": null,
    "image": "programming-hands.jpg",
    "requiresQuote": false,
    "installationIncluded": true,
    "unitLabel": "שעות"
  },
  {
    "id": "shutter-230v",
    "sku": "",
    "name": "מתאם אלחוטי לתריס 230V",
    "description": "כולל התקנה.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 47966,
    "maxNetCents": null,
    "image": "micromodule.jpg",
    "requiresQuote": false,
    "installationIncluded": true
  },
  {
    "id": "shutter-24v",
    "sku": "TW303200-916-E",
    "name": "מתאם אלחוטי לתריס 24V כלוא בזכוכית",
    "description": "כולל התקנה. בכמויות מסוימות יידרש ספק כוח 24V 4.2A נוסף; התאמה סופית לאחר בדיקת הדירה.",
    "category": "חשמל חכם Z-Wave בתדר 916 המותאם לישראל",
    "netCents": 83051,
    "maxNetCents": null,
    "image": "micromodule-24v.jpg",
    "requiresQuote": false,
    "installationIncluded": true
  },
  {
    "id": "floor-speaker-kit",
    "sku": "1220ENC",
    "name": "סט רמקולים לווייניים לבן 5.1 ALCYONE של Cabasse",
    "description": "מערכת קווית. ההתקנה אינה כוללת הכנת תשתית. נדרשות הכנות של החשמלאי.",
    "category": "אודיו",
    "netCents": 531000,
    "maxNetCents": null,
    "image": "audio-satellites.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 79500
  },
  {
    "id": "soundbar",
    "sku": "מקרני קול",
    "name": "סאונדבר אלחוטי איכותי לסלון, כולל סאב ומתלה אלחוטי",
    "description": "מגוון מוצרים בהתאמה לדייר; נדרש שקע חשמל בלבד.",
    "category": "אודיו",
    "netCents": 141600,
    "maxNetCents": 335000,
    "image": "soundbar-klipsch.jpg",
    "requiresQuote": true,
    "installationIncluded": false,
    "installationNetCents": 69500
  },
  {
    "id": "alarm-contact-motion",
    "sku": "10000",
    "name": "גלאי מגנט או גלאי נפח אלחוטי מבוסס סוללה",
    "description": "דורש רכזת אזעקה אלחוטית",
    "category": "אזעקה אלחוטית",
    "netCents": 37000,
    "maxNetCents": null,
    "image": "detector-magnetic-risco-x78-x73.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "smoke-detector",
    "sku": "10000",
    "name": "גלאי עשן אלחוטי מבוסס סוללה",
    "description": "דורש רכזת אזעקה אלחוטית",
    "category": "אזעקה אלחוטית",
    "netCents": 38500,
    "maxNetCents": null,
    "image": "detector-smoke-risco-x35s.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "flood-detector",
    "sku": "10000",
    "name": "גלאי הצפה אלחוטי מבוסס סוללה",
    "description": "דורש רכזת אזעקה אלחוטית",
    "category": "אזעקה אלחוטית",
    "netCents": 34500,
    "maxNetCents": null,
    "image": "detector-flood.jpg",
    "requiresQuote": false,
    "installationIncluded": false,
    "installationNetCents": 29500
  },
  {
    "id": "alarm-kit",
    "sku": "10000",
    "name": "חבילת אזעקה אלחוטית RISCO WiComm Pro כולל חיבור לבית חכם והתקנה",
    "description": "כולל רכזת וצופר עם סוללת גיבוי, גלאי נפח פנימי, גלאי מגנט פנימי, שלט ולוח מקשים; חיבור לבית החכם, הגדרה וחיבור ראשוני לאפליקציה, בדיקת פעולה והדרכה בסיסית. המחיר לפני מע״מ וכולל התקנה בתיאום מחלקת השירות. שירותי ענן RISCO, מנוי, SIM וחיבור למוקד אינם כלולים.",
    "category": "אזעקה אלחוטית",
    "netCents": 296610,
    "maxNetCents": null,
    "image": "alarm-system.jpg",
    "requiresQuote": false,
    "installationIncluded": true
  },
  {
    "id": "glass-power-socket",
    "name": "שקע זכוכית יחיד כולל מסגרת זכוכית",
    "description": "המחיר כולל את השקע ואת מסגרת הזכוכית. כולל התקנה. נדרשת התאמה לקופסת החשמל ולתשתית הקיימת.",
    "image": "white-glass-power-socket.jpg",
    "sku": "",
    "category": "שקעים ומנגנוני זכוכית",
    "netCents": 17500,
    "maxNetCents": null,
    "requiresQuote": false,
    "installationIncluded": true
  },
  {
    "id": "glass-double-socket",
    "name": "שקע זכוכית כפול כולל מסגרת זכוכית",
    "description": "המחיר כולל את השקע ואת מסגרת הזכוכית. כולל התקנה. נדרשת התאמה לקופסת החשמל ולתשתית הקיימת.",
    "image": "",
    "sku": "",
    "category": "שקעים ומנגנוני זכוכית",
    "netCents": 27500,
    "maxNetCents": null,
    "requiresQuote": false,
    "installationIncluded": true
  }
]
CATALOG
, true, 512, JSON_THROW_ON_ERROR);
