<?php if (!isset($user) || $user === null) { http_response_code(404); exit; } ?>
<section class="guide" id="app-guide" aria-labelledby="app-title">
<p class="eyebrow">הבית החכם — גם מהטלפון</p><h2 id="app-title">איך משתמשים באפליקציית TouchWand?</h2>
<p>ההדרכה מיועדת לדירות עם מערכת TouchWand. אם הוחלף הבקר או הותקנה מערכת אחרת, השתמשו בפרטי ההדרכה שנמסרו עם המערכת שלכם.</p>
<p class="notice">הכניסה לאזור הדיירים נעשית בקוד למייל. השליטה בבית נעשית עם שם המשתמש והסיסמה של מערכת הבית החכם שנמסרו לכם בהתקנה.</p>
<div class="guide-grid">
<article><h3>iPhone ו־iPad</h3><ol><li>פתחו את Safari והיכנסו ל־<a href="https://cloud.touchwand.com" target="_blank" rel="noopener noreferrer">cloud.touchwand.com</a>.</li><li>התחברו עם שם המשתמש והסיסמה הקיימים של מערכת TouchWand.</li><li>בתפריט השיתוף בחרו „הוספה למסך הבית” כדי ליצור קיצור דרך נוח.</li><li>בכניסה הבאה פתחו את הקיצור ממסך הבית.</li></ol><a class="action-link" href="https://cloud.touchwand.com" target="_blank" rel="noopener noreferrer">פתיחת מערכת TouchWand</a></article>
<article><h3>Android</h3><ol><li>פתחו את אפליקציית TouchWand הקיימת בטלפון.</li><li>התחברו עם פרטי המערכת שנמסרו לכם.</li><li>אם האפליקציה אינה מותקנת, היכנסו למדריך ההתקנה של I Feel שבו מופיעים קובץ ההתקנה והשלבים.</li><li>אפשר להיכנס גם דרך <a href="https://cloud.touchwand.com" target="_blank" rel="noopener noreferrer">אתר הענן</a>.</li></ol><a class="action-link" href="https://i-feel.co.il/touchwand-app/" target="_blank" rel="noopener noreferrer">הורדה והוראות התקנה</a></article>
<article><h3>תאורה, תריסים ותרחישים</h3><p>לאחר הכניסה בחרו את החדר או את הרכיב שברצונכם להפעיל. האפשרויות תלויות בציוד שהותקן ובתכנות שבוצע בדירה.</p><p>תרחישים ותזמונים פועלים בהתאם להגדרות שנמסרו לכם. לשינוי שמות, התאמת תרחיש או הוספת רכיב ניתן לתאם שירות תכנות לפי המחירון.</p><a class="action-link" href="https://i-feel.co.il/video/" target="_blank" rel="noopener noreferrer">ספריית סרטוני ההדרכה</a></article>
<article><h3>לא מצליחים להתחבר?</h3><p>בדקו שהטלפון מחובר לאינטרנט ושפרטי ההתחברות נכונים. אם המערכת לא מופיעה, אינה מגיבה או שפרטי הכניסה חסרים, פנו לשירות עם שם הפרויקט ומספר הדירה.</p><p>אין צורך לפרסם או לשלוח סיסמה בפנייה.</p><a class="action-link" href="https://i-feel.co.il/service-request/" target="_blank" rel="noopener noreferrer">פתיחת קריאת שירות</a> <a class="action-link" href="tel:035089553">03-508-9553</a></article>
</div></section>
<section class="guide" id="how-to-order"><h2>איך מוסיפים ציוד לדירה?</h2><ol><li><strong>בוחרים ציוד וכמויות</strong> — הרשימה מחשבת ציוד, התקנה ומע״מ בנפרד. שירות תכנות מחושב לפי שעות.</li><li><strong>מתאמים בדיקת התאמה</strong> — בודקים את הבקר, סוג המפסקים, התדר והתשתית הקיימת. התאמה למערכת נבדקת לפני הזמנה.</li><li><strong>מאשרים ומתקינים</strong> — לאחר סיכום המחיר והעבודה מתאמים התקנה, שיוך הרכיבים למערכת והדרכה על השימוש.</li></ol><p class="small">עבודות חשמלאי והכנת תשתית אינן כלולות אלא אם סוכם אחרת במפורש. אין בעמוד זה התחייבות שכל מוצר מתאים לכל דירה.</p></section>
